/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 casio.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/casio.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, -0.002, 0]}>
        <primitive object={nodes.Bone} />
        <skinnedMesh geometry={nodes.Digital_Wristwatch.geometry} material={materials.Digital_Wristwatch} skeleton={nodes.Digital_Wristwatch.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/casio.gltf')
